SP500_TICKERS = [
    "AAPL", "MSFT", "GOOGL", "AMZN", "NVDA", "META", "TSLA", "BRK.B", "UNH", "JNJ",
    "V", "XOM", "JPM", "WMT", "MA", "PG", "CVX", "HD", "LLY", "ABBV",
    "MRK", "PFE", "AVGO", "KO", "PEP", "COST", "TMO", "BAC", "MCD", "CSCO",
    "ACN", "DIS", "ABT", "DHR", "WFC", "NKE", "VZ", "ADBE", "CRM", "TXN",
    "NEE", "PM", "BMY", "UNP", "RTX", "HON", "QCOM", "LOW", "INTC", "UPS",
    "AMD", "AMGN", "IBM", "GS", "CAT", "SBUX", "BLK", "DE", "INTU", "MDT",
    "GILD", "SPGI", "BKNG", "ISRG", "C", "TJX", "MO", "ADP", "VRTX", "REGN",
    "CVS", "CI", "PLD", "SYK", "BDX", "CME", "CB", "SO", "DUK", "NOC",
    "ETN", "BSX", "EOG", "TGT", "SLB", "ZTS", "AON", "CL", "MCK", "PNC",
    "ITW", "SHW", "APD", "MMC", "ELV", "NSC", "MAR", "ICE", "WM", "EMR",
    "AEP", "PH", "KLAC", "MCO", "ORLY", "COF", "PSX", "MU", "TFC", "LRCX",
    "AIG", "AMAT", "NXPI", "HUM", "PNC", "USB", "FCX", "EIX", "GD", "MSI",
    "GM", "BK", "TMUS", "ECL", "NEM", "SCHW", "AMP", "CMG", "PCAR", "TGT",
    "SYY", "AZO", "WELL", "MCHP", "CTVA", "ROP", "AFL", "CARR", "PAYX", "HCA",
    "STZ", "A", "ORCL", "ADSK", "CTAS", "CSX", "CMI", "PPG", "F", "D",
    "PSA", "APTV", "DHI", "RSG", "KMB", "TROW", "AME", "TRV", "LMT", "FTNT",
    "LHX", "PCG", "KMI", "CAT", "TEL", "DLR", "MSCI", "SBAC", "O", "EXC",
    "KDP", "CTSH", "GLW", "YUM", "CMI", "KHC", "GD", "VRSK", "DD", "NSC",
    "FAST", "ROK", "IDXX", "CTSH", "WMB", "PCLN", "ANSS", "ODFL", "PAYC", "DLTR",
    "CDNS", "WEC", "KEYS", "MLM", "VMC", "ROST", "BIIB", "EBAY", "EXR", "PCG",
    "DOV", "CDW", "GWW", "PCAR", "TT", "AWK", "TSCO", "DOW", "FITB", "SBAC",
    "PPL", "XYL", "TSN", "DFS", "OTIS", "GE", "IQV", "BKR", "MTD", "TTWO",
    "TDY", "ALGN", "CDW", "HSY", "VRSN", "SYF", "DHI", "ANET", "HES", "NVR",
    "CDNS", "WST", "TER", "CPRT", "ALB", "EA", "MTCH", "OKTA", "SWK", "VICI",
    "EXPE", "ZBH", "AVY", "DFS", "ARE", "CF", "CTLT", "DTM", "EFX", "ENPH",
    "ES", "EXPD", "FANG", "HBAN", "HOLX", "INVH", "KEY", "KRTX", "LYB", "MRO",
    "NTRS", "PTC", "RF", "RMD", "SGEN", "TMUS", "TSN", "TT", "UDR", "VTR",
    "WBA", "WAT", "WELL", "WYNN", "ZBRA", "ZION", "ABMD", "ACGL", "ADBE", "AEE",
    "AEP", "AGNC", "AIV", "AIZ", "AJG", "ALGN", "ALL", "ALLE", "AMAT", "AMCR",
    "AMED", "AMP", "ANSS", "AON", "APD", "APG", "APH", "ARE", "ATO", "ATVI",
    "AVB", "AVY", "AWK", "AXP", "AZO", "BA", "BALL", "BBY", "BDX", "BEN",
    "BIIB", "BKR", "BLK", "BMY", "BR", "BRO", "BSX", "BWA", "BXP", "CAG",
    "CAH", "CARR", "CB", "CBRE", "CCI", "CCL", "CDE", "CE", "CFG", "CHRW",
    "CI", "CL", "CLX", "CMA", "CMCSA", "CME", "CMI", "CMS", "CNP", "COF",
    "COO", "COP", "COST", "COTY", "CPB", "CPRT", "CRL", "CRM", "CSCO", "CSX",
    "CTAS", "CTLT", "CTSH", "CVS", "CVX", "CZR", "D", "DAL", "DASH", "DBX",
    "DCI", "DCO", "DE", "DFS", "DG", "DGX", "DHI", "DHR", "DIS", "DISCA",
    "DISH", "DLR", "DLTR", "DOV", "DRI", "DT", "DTE", "DUK", "DVA", "DVN",
    "DXC", "DXCM", "EA", "EBAY", "ECL", "ED", "EFX", "EL", "ELV", "EMN",
    "EMR", "ENPH", "EOG", "EPAM", "EQIX", "EQR", "ES", "ESS", "ETN", "ETR",
    "EVRG", "EXC", "EXPD", "EXPE", "EXR", "F", "FANG", "FAST", "FB", "FCX",
    "FDS", "FDX", "FE", "FFIV", "FIS", "FISV", "FITB", "FLT", "FMC", "FOX",
    "FRC", "FRT", "FTNT", "FTV", "GD", "GDS", "GE", "GHC", "GLW", "GM",
    "GOOGL", "GPC", "GPN", "GS", "GWW", "HAL", "HAS", "HCA", "HCP", "HD",
    "HES", "HII", "HLT", "HOC", "HOG", "HOLX", "HON", "HP", "HPQ", "HRL",
    "HSIC", "HSY", "HUM", "HWM", "IBM", "ICE", "ICR", "IDXX", "IEX", "IFF",
    "ILMN", "INCY", "INFO", "INFY", "INTU", "INVH", "IONS", "IP", "IPG", "IR",
    "IRM", "ISRG", "IT", "ITW", "IVZ", "JBHT", "JCI", "JKHY", "JNJ", "JPM",
    "JWN", "K", "KDP", "KEY", "KEYS", "KHC", "KIM", "KLAC", "KMB", "KMI",
    "KMX", "KNX", "KO", "KR", "KRC", "KRTX", "KSS", "KTB", "KTI", "L",
    "LC", "LDOS", "LEG", "LEN", "LH", "LHC", "LHX", "LIN", "LKQ", "LLY",
    "LMT", "LNC", "LNT", "LOW", "LRCX", "LSX", "LUV", "LVS", "LW", "LYB",
    "LYV", "M", "MA", "MAA", "MAR", "MAS", "MCHP", "MCK", "MCO", "MDLZ",
    "MDT", "MET", "MGM", "MHK", "MIC", "MKC", "MLM", "MMC", "MMM", "MO",
    "MOH", "MOS", "MPC", "MRK", "MRO", "MS", "MSCI", "MSFT", "MTB", "MTCH",
    "MTD", "MU", "MXIM", "MKC", "NAV", "NCLH", "NCR", "NDAQ", "NDSN", "NEE",
    "NEM", "NFLX", "NI", "NKE", "NLSN", "NOC", "NOV", "NOW", "NRG", "NSC",
    "NTAP", "NTNX", "NTRS", "NUE", "NVDA", "NVR", "NWL", "O", "ODFL", "OIH",
    "OKE", "OMC", "ON", "ORCL", "ORLY", "OSK", "OXY", "PAYC", "PAYX", "PCAR",
    "PCG", "PCH", "PCLN", "PCM", "PCMI", "PD", "PEG", "PENN", "PEP", "PFE",
    "PFG", "PG", "PGR", "PH", "PHM", "PKG", "PKI", "PLD", "PM", "PNC", "PNW",
    "POOL", "PPG", "PPL", "PRGO", "PRU", "PSA", "PTC", "PWR", "PYPL", "QCOM",
    "QRVO", "R", "RBA", "RCL", "REG", "REGN", "RF", "RHI", "RHT", "RJF",
    "RL", "RMD", "ROK", "ROL", "ROP", "ROST", "RRC", "RSG", "RTX", "RVLN",
    "RWAY", "SBAC", "SBUX", "SCCO", "SCHW", "SE", "SEE", "SHW", "SIRI",
    "SITE", "SIVB", "SLB", "SLG", "SNA", "SNAP", "SNPS", "SO", "SPG",
    "SPGI", "SRE", "STT", "STZ", "SWK", "SWKS", "SYF", "SYK", "SYY", "T",
    "TAP", "TCF", "TDG", "TDI", "TDY", "TEL", "TER", "TFC", "TGT", "TJX",
    "TMO", "TMUS", "TROW", "TRV", "TSCO", "TSLA", "TSN", "TT", "TTWO",
    "TWLO", "TXN", "TXT", "TYL", "UA", "UAA", "UAL", "UDR", "UHS", "ULTA",
    "UNH", "UNP", "UPS", "URBN", "USB", "V", "VARS", "VEEV", "VFC", "VIAB",
    "VICI", "VLO", "VMC", "VMI", "VNO", "VRSK", "VRSN", "VRTX", "VTR",
    "VTVT", "VZ", "WAB", "WAT", "WBA", "WBC", "WDC", "WEC", "WELL", "WFC",
    "WHR", "WM", "WMB", "WMT", "WRK", "WST", "WTW", "WY", "WYNN", "XEL",
    "XLNX", "XOM", "XRAY", "XYL", "YUM", "ZBH", "ZION", "ZS", "ZTS"
]
